Traceback (most recent call last):
  File "C:\Users\akhyar\AppData\Roaming\Python\Python311\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Program Files\Python311\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Program Files\Python311\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Program Files\Python311\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Make predictions
y_pred = model.predict(X_test)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Cell [1;32mIn[9], line 2[0m
[0;32m      1[0m [38;5;66;03m# Make predictions[39;00m
[1;32m----> 2[0m y_pred [38;5;241m=[39m [43mmodel[49m[38;5;241;43m.[39;49m[43mpredict[49m[43m([49m[43mX_test[49m[43m)[49m

File [1;32mC:\Program Files\Python311\Lib\site-packages\sklearn\linear_model\_base.py:351[0m, in [0;36mLinearClassifierMixin.predict[1;34m(self, X)[0m
[0;32m    337[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[0;32m    338[0m [38;5;124;03mPredict class labels for samples in X.[39;00m
[0;32m    339[0m 
[1;32m   (...)[0m
[0;32m    348[0m [38;5;124;03m    Vector containing the class labels for each sample.[39;00m
[0;32m    349[0m [38;5;124;03m"""[39;00m
[0;32m    350[0m xp, _ [38;5;241m=[39m get_namespace(X)
[1;32m--> 351[0m scores [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdecision_function[49m[43m([49m[43mX[49m[43m)[49m
[0;32m    352[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(scores[38;5;241m.[39mshape) [38;5;241m==[39m [38;5;241m1[39m:
[0;32m    353[0m     indices [38;5;241m=[39m xp[38;5;241m.[39mastype(scores [38;5;241m>[39m [38;5;241m0[39m, [38;5;28mint[39m)

File [1;32mC:\Program Files\Python311\Lib\site-packages\sklearn\linear_model\_base.py:332[0m, in [0;36mLinearClassifierMixin.decision_function[1;34m(self, X)[0m
[0;32m    329[0m check_is_fitted([38;5;28mself[39m)
[0;32m    330[0m xp, _ [38;5;241m=[39m get_namespace(X)
[1;32m--> 332[0m X [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_validate_data[49m[43m([49m[43mX[49m[43m,[49m[43m [49m[43maccept_sparse[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mcsr[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mreset[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m
[0;32m    333[0m scores [38;5;241m=[39m safe_sparse_dot(X, [38;5;28mself[39m[38;5;241m.[39mcoef_[38;5;241m.[39mT, dense_output[38;5;241m=[39m[38;5;28;01mTrue[39;00m) [38;5;241m+[39m [38;5;28mself[39m[38;5;241m.[39mintercept_
[0;32m    334[0m [38;5;28;01mreturn[39;00m xp[38;5;241m.[39mreshape(scores, ([38;5;241m-[39m[38;5;241m1[39m,)) [38;5;28;01mif[39;00m scores[38;5;241m.[39mshape[[38;5;241m1[39m] [38;5;241m==[39m [38;5;241m1[39m [38;5;28;01melse[39;00m scores

File [1;32mC:\Program Files\Python311\Lib\site-packages\sklearn\base.py:608[0m, in [0;36mBaseEstimator._validate_data[1;34m(self, X, y, reset, validate_separately, cast_to_ndarray, **check_params)[0m
[0;32m    537[0m [38;5;28;01mdef[39;00m [38;5;21m_validate_data[39m(
[0;32m    538[0m     [38;5;28mself[39m,
[0;32m    539[0m     X[38;5;241m=[39m[38;5;124m"[39m[38;5;124mno_validation[39m[38;5;124m"[39m,
[1;32m   (...)[0m
[0;32m    544[0m     [38;5;241m*[39m[38;5;241m*[39mcheck_params,
[0;32m    545[0m ):
[0;32m    546[0m [38;5;250m    [39m[38;5;124;03m"""Validate input data and set or check the `n_features_in_` attribute.[39;00m
[0;32m    547[0m 
[0;32m    548[0m [38;5;124;03m    Parameters[39;00m
[1;32m   (...)[0m
[0;32m    606[0m [38;5;124;03m        validated.[39;00m
[0;32m    607[0m [38;5;124;03m    """[39;00m
[1;32m--> 608[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_check_feature_names[49m[43m([49m[43mX[49m[43m,[49m[43m [49m[43mreset[49m[38;5;241;43m=[39;49m[43mreset[49m[43m)[49m
[0;32m    610[0m     [38;5;28;01mif[39;00m y [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m [38;5;28mself[39m[38;5;241m.[39m_get_tags()[[38;5;124m"[39m[38;5;124mrequires_y[39m[38;5;124m"[39m]:
[0;32m    611[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m    612[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mThis [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39m[38;5;18m__class__[39m[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m estimator [39m[38;5;124m"[39m
[0;32m    613[0m             [38;5;124m"[39m[38;5;124mrequires y to be passed, but the target y is None.[39m[38;5;124m"[39m
[0;32m    614[0m         )

File [1;32mC:\Program Files\Python311\Lib\site-packages\sklearn\base.py:535[0m, in [0;36mBaseEstimator._check_feature_names[1;34m(self, X, reset)[0m
[0;32m    530[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m missing_names [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m unexpected_names:
[0;32m    531[0m     message [38;5;241m+[39m[38;5;241m=[39m (
[0;32m    532[0m         [38;5;124m"[39m[38;5;124mFeature names must be in the same order as they were in fit.[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[0;32m    533[0m     )
[1;32m--> 535[0m [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(message)

[1;31mValueError[0m: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- 00
- 000
- 01
- 02
- 029
- ...
Feature names seen at fit time, yet now missing:
- 0
- 0.1
- 1
- 2
- 29.1
- ...


